


WAX_VERSION_MAJOR = 0
WAX_VERSION_MINOR = 1
WAX_VERSION_PATCH = 1

WAX_VERSION = f"{WAX_VERSION_MAJOR}.{WAX_VERSION_MINOR}.{WAX_VERSION_PATCH}"
WAX_VERSION_NUMBER = (WAX_VERSION_MAJOR * 256) + (WAX_VERSION_MINOR * 16) + WAX_VERSION_PATCH


